services:
  hello-world-api:
    container_name: hello-world-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PREFIX="Hello World !"
    ports:
      - "8080:8080"
